# theme = "terminal_colors"
theme = "rust"

[editor]
line-number = "relative"
completion-trigger-len = 1
idle-timeout = 100

[editor.soft-wrap]
enable = false

[editor.lsp]
display-inlay-hints = true

[editor.statusline]
right = ["version-control", "diagnostics", "selections", "position", "file-encoding"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
S = ["extend_line_below", "delete_selection", "open_above"]
C = ["ensure_selections_forward", "extend_to_line_end", "change_selection"]
D = ["ensure_selections_forward", "kill_to_line_end"]
X = "extend_line_above"

"C-j" = "copy_selection_on_next_line"
"C-k" = "copy_selection_on_prev_line"
"C-n" = ["search_selection", "extend_search_next"]
"C-p" = ["search_selection", "extend_search_prev"]
"C-s" = ":write"

[keys.normal.space]
q = ":q"
Q = ":xa"
"space" = ["add_newline_above", "add_newline_below"]
l = { h = ":toggle-option lsp.display-inlay-hints" }

