# Language support configuration.
# See the languages documentation: https://docs.helix-editor.com/master/languages.html

[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rust"
file-types = ["rs"]
#roots = ["Cargo.toml", "Cargo.lock"]
auto-format = true
comment-token = "//"
language-server = { command = "rust-analyzer" }
indent = { tab-width = 4, unit = "    " }

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'|' = '|'
#'`' = '`'

[language.config]
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false
inlayHints.typeHints.hideNamedConstructor = true
semanticHighlighting.punctuation.enable = true
semanticHighlighting.operator.specialization.enable = true
typing.autoClosingAngleBrackets.enable = true
check.command = "clippy"
rustfmt.extraArgs = []

[[language]]
name = "haskell"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "elm"
auto-format = true
formatter = { command = "elm-format" , args = ["--stdin"] }
