inherits = "everforest_dark"

"ui.virtual.inlay-hint" = { fg = "virtual", modifiers = ["italic"] }

[palette]
bg0 = "#181818"
bg1 = "#202020"
bg2 = "#222222"
bg3 = "#242424"
bg4 = "#262626"
virtual = "#5D5D5D"
